conventions:
  date_format: "YYYY-MM-DD"
  link_style: "wikilink"
  create_if_missing: false
  status:
    default: "draft"
    allowed:
      - draft
      - in-progress
      - review
      - published
      - archived

schemas:
  frontmatter:
    required:
      - title
      - status
    optional:
      - tags
      - aliases
    enums:
      status:
        - draft
        - in-progress
        - review
        - published
        - archived
  templates:
    study_note:
      required_sections:
        - Summary
        - References
    deep_dive:
      required_sections:
        - Concepts
        - Decisions
        - References

routes:
  - id: topic/example/overview
    pattern: "topic/example/overview/*.md"
    topic: example
    template: study_note
    tags:
      - ref/overview
  - id: topic/example/deep
    pattern: "topic/example/deep/*.md"
    topic: example
    template: deep_dive
    required_sections:
      - Concepts
      - Decisions
      - References

health_checks:
  link_integrity: true
  multi_topic_sprawl:
    size_kb: 64
    max_headings: 12
    distinct_topics: 2
  required_sections:
    - route: topic/example/deep
      must_have:
        - Concepts
        - Decisions
        - References

acceptance:
  frontmatter_complete: true
  title_matches_h1: true
  body_min_length: 200
